Attribute VB_Name = "Module10"
Public Sub itemheightthickness()
    Sheets("constraint").Cells(2, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(2, 2).Value = "*"
    Sheets("constraint").Cells(2, 3).Value = "10480"
    Sheets("constraint").Cells(2, 4).Value = "contributor"
    Sheets("constraint").Cells(2, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(2, 6).Value = "max_occurs"
    Sheets("constraint").Cells(2, 8).Value = 1
    Sheets("constraint").Cells(2, 9).Value = "Insert"
    Sheets("constraint").Cells(3, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(3, 2).Value = "height.value"
    Sheets("constraint").Cells(3, 3).Value = "10480"
    Sheets("constraint").Cells(3, 4).Value = "contributor"
    Sheets("constraint").Cells(3, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(3, 6).Value = "min_value"
    Sheets("constraint").Cells(3, 9).Value = "Insert"
    Sheets("constraint").Cells(4, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(4, 2).Value = "height.value"
    Sheets("constraint").Cells(4, 3).Value = "10480"
    Sheets("constraint").Cells(4, 4).Value = "contributor"
    Sheets("constraint").Cells(4, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(4, 6).Value = "max_value"
    Sheets("constraint").Cells(4, 9).Value = "Insert"
    Sheets("constraint").Cells(5, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(5, 2).Value = "height.value"
    Sheets("constraint").Cells(5, 3).Value = "10480"
    Sheets("constraint").Cells(5, 4).Value = "contributor"
    Sheets("constraint").Cells(5, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(5, 6).Value = "max_scale"
    Sheets("constraint").Cells(5, 9).Value = "Insert"
    Sheets("constraint").Cells(6, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(6, 2).Value = "height.value"
    Sheets("constraint").Cells(6, 3).Value = "10480"
    Sheets("constraint").Cells(6, 4).Value = "contributor"
    Sheets("constraint").Cells(6, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(6, 6).Value = "max_precision"
    Sheets("constraint").Cells(6, 8).Value = 12
    Sheets("constraint").Cells(6, 9).Value = "Insert"
    Sheets("constraint").Cells(7, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(7, 2).Value = "height.unit"
    Sheets("constraint").Cells(7, 3).Value = "10480"
    Sheets("constraint").Cells(7, 4).Value = "contributor"
    Sheets("constraint").Cells(7, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(7, 6).Value = "enumeration"
    Sheets("constraint").Cells(7, 9).Value = "Insert"
    Sheets("constraint").Cells(8, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(8, 2).Value = "thickness.value"
    Sheets("constraint").Cells(8, 3).Value = "10480"
    Sheets("constraint").Cells(8, 4).Value = "contributor"
    Sheets("constraint").Cells(8, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(8, 6).Value = "min_value"
    Sheets("constraint").Cells(8, 9).Value = "Insert"
    Sheets("constraint").Cells(9, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(9, 2).Value = "thickness.value"
    Sheets("constraint").Cells(9, 3).Value = "10480"
    Sheets("constraint").Cells(9, 4).Value = "contributor"
    Sheets("constraint").Cells(9, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(9, 6).Value = "max_value"
    Sheets("constraint").Cells(9, 9).Value = "Insert"
    Sheets("constraint").Cells(10, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(10, 2).Value = "thickness.value"
    Sheets("constraint").Cells(10, 3).Value = "10480"
    Sheets("constraint").Cells(10, 4).Value = "contributor"
    Sheets("constraint").Cells(10, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(10, 6).Value = "max_scale"
    Sheets("constraint").Cells(10, 9).Value = "Insert"
    Sheets("constraint").Cells(11, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(11, 2).Value = "thickness.value"
    Sheets("constraint").Cells(11, 3).Value = "10480"
    Sheets("constraint").Cells(11, 4).Value = "contributor"
    Sheets("constraint").Cells(11, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(11, 6).Value = "max_precision"
    Sheets("constraint").Cells(11, 8).Value = 12
    Sheets("constraint").Cells(11, 9).Value = "Insert"
    Sheets("constraint").Cells(12, 1).Value = Worksheets("attribute").Cells(13, 3).Value
    Sheets("constraint").Cells(12, 2).Value = "thickness.unit"
    Sheets("constraint").Cells(12, 3).Value = "10480"
    Sheets("constraint").Cells(12, 4).Value = "contributor"
    Sheets("constraint").Cells(12, 5).Value = "PRODUCT"
    Sheets("constraint").Cells(12, 6).Value = "enumeration"
    Sheets("constraint").Cells(12, 9).Value = "Insert"
End Sub

